export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS';
export const SERVICE_START_LOADING = 'SERVICE_START_LOADING';
export const SERVICE_STOP_LOADING = 'SERVICE_STOP_LOADING';
