// actionTypes.js

export const GET_ALL_BUSINESSES_REQUEST = 'GET_ALL_BUSINESSES_REQUEST';
export const GET_ALL_BUSINESSES_SUCCESS = 'GET_ALL_BUSINESSES_SUCCESS';
export const GET_ALL_BUSINESSES_FAILURE = 'GET_ALL_BUSINESSES_FAILURE';

export const GET_BUSINESS_DETAILS_REQUEST = 'GET_BUSINESS_DETAILS_REQUEST';
export const GET_BUSINESS_DETAILS_SUCCESS = 'GET_BUSINESS_DETAILS_SUCCESS';
export const GET_BUSINESS_DETAILS_FAILURE = 'GET_BUSINESS_DETAILS_FAILURE';

// actionTypes.js

export const CREATE_BUSINESS_REQUEST = 'CREATE_BUSINESS_REQUEST';
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const CREATE_BUSINESS_FAILURE = 'CREATE_BUSINESS_FAILURE';

export const UPDATE_BUSINESS_PROFILE = 'UPDATE_BUSINESS_PROFILE';

