export const GET_ALL_BLOGS = 'GET_ALL_BLOGS';
export const GET_BLOG_DETAILS = 'GET_BLOG_DETAILS';
export const BLOG_START_LOADING = 'BLOG_START_LOADING';
export const BLOG_STOP_LOADING = 'BLOG_STOP_LOADING';
