export const CREATE_THEME = 'CREATE_THEME';
export const GET_ALL_THEMES = 'GET_ALL_THEMES';
export const GET_THEME_DETAILS = 'GET_THEME_DETAILS';
export const UPDATE_THEME = 'UPDATE_THEME';
export const DELETE_THEME = 'DELETE_THEME';

export const THEME_START_LOADING = 'THEME_START_LOADING';
export const THEME_STOP_LOADING = 'THEME_STOP_LOADING';
